# name of our workflow

name: Django CI/CD

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres_main:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: django_cicd
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requirements
        run: |
          cd ../..
          cd tutorial1
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          DEBUG: "0"
          DJANGO_SECRET_KEY: CI_CD_TEST_KEY
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: django_cicd
          POSTGRES_HOST: postgres_main
        run: |
          python manage.py test